// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Provides AI-powered tax guidance based on user selections.
 *
 * - taxGuidance - A function that provides tax guidance based on user selections.
 * - TaxGuidanceInput - The input type for the taxGuidance function.
 * - TaxGuidanceOutput - The return type for the taxGuidance function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const TaxGuidanceInputSchema = z.object({
  jenisTransaksi: z.string().describe('Jenis Transaksi.'),
  wp: z.string().describe('Wajib Pajak (WP) type.'),
  fakturPajak: z.string().describe('Faktur Pajak status.'),
  asnNonAsn: z.string().describe('ASN / NON ASN status.'),
  golongan: z.string().describe('Golongan (for ASN).'),
  sertifikatKonstruksi: z.string().describe('Sertifikat Konstruksi status.'),
  jenisPajak: z.string().optional().describe('Jenis Pajak.'),
  kodePajakEbillingPPh: z.string().optional().describe('Kode Pajak E-billing PPh.'),
  dppRasio: z.string().optional().describe('DPP Rasio.'),
  ptkp: z.string().optional().describe('PTKP (Penghasilan Tidak Kena Pajak).'),
  tarifPajak: z.string().optional().describe('Tarif Pajak.'),
  kenaPpn: z.string().optional().describe('Kena PPN (Pajak Pertambahan Nilai).'),
  kodePajakEbillingPpn: z.string().optional().describe('Kode Pajak E-billing PPN.'),
});
export type TaxGuidanceInput = z.infer<typeof TaxGuidanceInputSchema>;

const TaxGuidanceOutputSchema = z.object({
  guidance: z.string().describe('AI-powered tax guidance and clarifications.'),
});
export type TaxGuidanceOutput = z.infer<typeof TaxGuidanceOutputSchema>;

export async function taxGuidance(input: TaxGuidanceInput): Promise<TaxGuidanceOutput> {
  return taxGuidanceFlow(input);
}

const taxGuidancePrompt = ai.definePrompt({
  name: 'taxGuidancePrompt',
  input: {schema: TaxGuidanceInputSchema},
  output: {schema: TaxGuidanceOutputSchema},
  prompt: `You are an AI tax assistant. Based on the following selections, provide guidance and clarifications regarding the tax implications, including potential deductions, compliance requirements, and links to relevant regulations.

Selections:
Jenis Transaksi: {{{jenisTransaksi}}}
WP: {{{wp}}}
Faktur Pajak: {{{fakturPajak}}}
ASN / NON ASN: {{{asnNonAsn}}}
Golongan: {{{golongan}}}
Sertifikat Konstruksi: {{{sertifikatKonstruksi}}}
Jenis Pajak: {{{jenisPajak}}}
Kode Pajak E-billing PPh: {{{kodePajakEbillingPPh}}}
DPP Rasio: {{{dppRasio}}}
PTKP: {{{ptkp}}}
Tarif Pajak: {{{tarifPajak}}}
Kena PPN: {{{kenaPpn}}}
Kode Pajak E-billing PPN: {{{kodePajakEbillingPpn}}}

Guidance:`,
});

const taxGuidanceFlow = ai.defineFlow(
  {
    name: 'taxGuidanceFlow',
    inputSchema: TaxGuidanceInputSchema,
    outputSchema: TaxGuidanceOutputSchema,
  },
  async input => {
    const {output} = await taxGuidancePrompt(input);
    return output!;
  }
);
